sudo: required
dist: xenial
addons:
  apt:
    packages:
      - libseccomp-dev
  snaps:
  - hugo
before_install:
- sudo apt-get -y install curl gnupg software-properties-common
- wget -O- -q https://github.com/containerd/containerd/releases/download/v1.2.0/containerd-1.2.0.linux-amd64.tar.gz | sudo tar xpz -C /
- sudo wget https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64 -O /bin/runc && sudo chmod +x /bin/runc
- curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | sudo DARCH_TAG=v0.26.4 bash /dev/stdin
- sudo containerd &
- darch version
- sudo ctr version
- sudo runc --version
- sudo darch images pull godarch/ubuntu:cosmic
install:
- sudo apt-get --yes install snapd
- sudo snap install hugo
script:
- "./ci"
